/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NoteAttachmentTracker
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var path = __toESM(require("path"));
var EMPTY_FOLDER_ICON = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2v11z"></path><line x1="9" y1="14" x2="15" y2="14"></line></svg>`;
var DEFAULT_SETTINGS = {
  attachmentFolderPatterns: [{ pattern: "{$filename}_\u9644\u4EF6", enabled: true }],
  cleanupPatterns: [{ pattern: "_\u9644\u4EF6", enabled: true }],
  useSystemTrash: true,
  customTrashFolder: "_\u56DE\u6536\u7AD9"
};
var NoteAttachmentTracker = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    (0, import_obsidian.addIcon)("empty-folder-search", EMPTY_FOLDER_ICON);
    this.addRibbonIcon("empty-folder-search", "\u641C\u7D22\u7A7A\u6587\u4EF6\u5939", async () => {
      const emptyFolders = await this.findEmptyFolders();
      new EmptyFoldersModal(this.app, this, emptyFolders).open();
    });
    this.addSettingTab(new NoteAttachmentTrackerSettingTab(this.app, this));
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          this.handleNoteRename(file, oldPath);
        }
      })
    );
    this.addCommand({
      id: "search-empty-folders",
      name: "\u641C\u7D22\u7A7A\u6587\u4EF6\u5939",
      callback: async () => {
        const emptyFolders = await this.findEmptyFolders();
        new EmptyFoldersModal(this.app, this, emptyFolders).open();
      }
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async handleNoteRename(file, oldPath) {
    const newPath = file.path;
    const oldFileName = path.basename(oldPath, path.extname(oldPath));
    const newFileName = path.basename(newPath, path.extname(newPath));
    const oldDir = path.dirname(oldPath);
    const newDir = path.dirname(newPath);
    for (const pattern of this.settings.attachmentFolderPatterns) {
      if (!pattern.enabled)
        continue;
      const oldFolderName = this.replacePlaceholders(pattern.pattern, oldFileName);
      const newFolderName = this.replacePlaceholders(pattern.pattern, newFileName);
      const oldFolderPath = (0, import_obsidian.normalizePath)(path.join(oldDir, oldFolderName));
      const newFolderPath = (0, import_obsidian.normalizePath)(path.join(newDir, newFolderName));
      const oldFolder = this.app.vault.getAbstractFileByPath(oldFolderPath);
      if (oldFolder instanceof import_obsidian.TFolder) {
        try {
          await this.app.fileManager.renameFile(oldFolder, newFolderPath);
          new import_obsidian.Notice(`\u5DF2\u79FB\u52A8\u5173\u8054\u6587\u4EF6\u5939: ${oldFolderPath} -> ${newFolderPath}`);
        } catch (error) {
          console.error("\u79FB\u52A8\u5173\u8054\u6587\u4EF6\u5939\u5931\u8D25:", error);
          new import_obsidian.Notice(`\u79FB\u52A8\u5173\u8054\u6587\u4EF6\u5939\u5931\u8D25: ${oldFolderPath} -> ${newFolderPath}`);
        }
      }
    }
  }
  // 替换模板中的占位符
  replacePlaceholders(pattern, filename) {
    return pattern.replace("{$filename}", filename);
  }
  // 搜索空的匹配文件夹
  async findEmptyFolders() {
    const emptyFolders = [];
    const vault = this.app.vault;
    const allFolders = vault.getAllLoadedFiles().filter((file) => file instanceof import_obsidian.TFolder);
    for (const folder of allFolders) {
      const matchesPattern = this.settings.cleanupPatterns.some(
        (pattern) => pattern.enabled && folder.path.includes(pattern.pattern)
      );
      if (matchesPattern) {
        const children = folder.children || [];
        if (children.length === 0) {
          emptyFolders.push(folder.path);
        }
      }
    }
    return emptyFolders;
  }
  // 删除文件夹（移动到垃圾箱或自定义回收站）
  async deleteFolder(folderPath) {
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!(folder instanceof import_obsidian.TFolder)) {
      throw new Error(`\u65E0\u6CD5\u627E\u5230\u6587\u4EF6\u5939: ${folderPath}`);
    }
    if (this.settings.useSystemTrash) {
      await this.app.vault.trash(folder, true);
    } else {
      const customTrashPath = (0, import_obsidian.normalizePath)(this.settings.customTrashFolder);
      const newPath = (0, import_obsidian.normalizePath)(path.join(customTrashPath, folder.name));
      if (!await this.app.vault.adapter.exists(customTrashPath)) {
        await this.app.vault.createFolder(customTrashPath);
      }
      await this.app.fileManager.renameFile(folder, newPath);
    }
    new import_obsidian.Notice(`\u5DF2\u5220\u9664\u6587\u4EF6\u5939: ${folderPath}`);
  }
};
var EmptyFoldersModal = class extends import_obsidian.Modal {
  constructor(app, plugin, emptyFolders) {
    super(app);
    this.plugin = plugin;
    this.emptyFolders = emptyFolders;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "\u7A7A\u6587\u4EF6\u5939\u6E05\u7406" });
    if (this.emptyFolders.length === 0) {
      contentEl.createEl("p", { text: "\u672A\u627E\u5230\u5339\u914D\u7684\u7A7A\u6587\u4EF6\u5939\u3002" });
      return;
    }
    const folderList = contentEl.createEl("div", { cls: "empty-folders-list" });
    for (const folderPath of this.emptyFolders) {
      const folderItem = folderList.createEl("div", { cls: "empty-folder-item" });
      folderItem.createEl("span", { text: folderPath, cls: "folder-path" });
      const deleteBtn = folderItem.createEl("button", { text: "\u5220\u9664", cls: "folder-delete-btn" });
      deleteBtn.addEventListener("click", async () => {
        try {
          await this.plugin.deleteFolder(folderPath);
          folderItem.remove();
          this.emptyFolders = this.emptyFolders.filter((p) => p !== folderPath);
          if (this.emptyFolders.length === 0) {
            this.close();
            new import_obsidian.Notice("\u6240\u6709\u7A7A\u6587\u4EF6\u5939\u5DF2\u6E05\u7406\u5B8C\u6210");
          }
        } catch (error) {
          console.error("\u5220\u9664\u6587\u4EF6\u5939\u5931\u8D25:", error);
          new import_obsidian.Notice(`\u5220\u9664\u6587\u4EF6\u5939\u5931\u8D25: ${folderPath}`);
        }
      });
    }
    const footerEl = contentEl.createEl("div", { cls: "empty-folders-footer" });
    const deleteAllBtn = footerEl.createEl("button", { text: "\u5168\u90E8\u5220\u9664", cls: "delete-all-btn" });
    deleteAllBtn.addEventListener("click", async () => {
      const totalCount = this.emptyFolders.length;
      let successCount = 0;
      for (const folderPath of [...this.emptyFolders]) {
        try {
          await this.plugin.deleteFolder(folderPath);
          successCount++;
          this.emptyFolders = this.emptyFolders.filter((p) => p !== folderPath);
        } catch (error) {
          console.error("\u5220\u9664\u6587\u4EF6\u5939\u5931\u8D25:", error);
        }
      }
      this.close();
      new import_obsidian.Notice(`\u5DF2\u5220\u9664 ${successCount}/${totalCount} \u4E2A\u7A7A\u6587\u4EF6\u5939`);
    });
    const cancelBtn = footerEl.createEl("button", { text: "\u53D6\u6D88", cls: "cancel-btn" });
    cancelBtn.addEventListener("click", () => {
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var NoteAttachmentTrackerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u7B14\u8BB0\u5173\u8054\u6539\u53D8 - \u8BBE\u7F6E" });
    containerEl.createEl("h3", { text: "\u5173\u8054\u6587\u4EF6\u5939\u8BBE\u7F6E" });
    const attachmentPatternsContainer = containerEl.createDiv("attachment-patterns-container");
    this.plugin.settings.attachmentFolderPatterns.forEach((pattern, index) => {
      this.addAttachmentPatternSetting(attachmentPatternsContainer, pattern, index);
    });
    new import_obsidian.Setting(containerEl).setName("\u6DFB\u52A0\u5173\u8054\u6587\u4EF6\u5939\u6A21\u5F0F").setDesc("\u6DFB\u52A0\u65B0\u7684\u5173\u8054\u6587\u4EF6\u5939\u547D\u540D\u6A21\u5F0F").addButton((button) => button.setButtonText("+").onClick(async () => {
      this.plugin.settings.attachmentFolderPatterns.push({
        pattern: "{$filename}_\u9644\u4EF6",
        enabled: true
      });
      await this.plugin.saveSettings();
      this.display();
    }));
    containerEl.createEl("h3", { text: "\u7A7A\u6587\u4EF6\u5939\u6E05\u7406\u8BBE\u7F6E" });
    const cleanupPatternsContainer = containerEl.createDiv("cleanup-patterns-container");
    this.plugin.settings.cleanupPatterns.forEach((pattern, index) => {
      this.addCleanupPatternSetting(cleanupPatternsContainer, pattern, index);
    });
    new import_obsidian.Setting(containerEl).setName("\u6DFB\u52A0\u6E05\u7406\u5339\u914D\u6A21\u5F0F").setDesc("\u6DFB\u52A0\u65B0\u7684\u7A7A\u6587\u4EF6\u5939\u5339\u914D\u6A21\u5F0F").addButton((button) => button.setButtonText("+").onClick(async () => {
      this.plugin.settings.cleanupPatterns.push({
        pattern: "_\u9644\u4EF6",
        enabled: true
      });
      await this.plugin.saveSettings();
      this.display();
    }));
    new import_obsidian.Setting(containerEl).setName("\u641C\u7D22\u7A7A\u6587\u4EF6\u5939").setDesc("\u6839\u636E\u5339\u914D\u6A21\u5F0F\u641C\u7D22\u7A7A\u6587\u4EF6\u5939").addButton((button) => button.setButtonText("\u641C\u7D22").onClick(async () => {
      const emptyFolders = await this.plugin.findEmptyFolders();
      new EmptyFoldersModal(this.app, this.plugin, emptyFolders).open();
    }));
    containerEl.createEl("h3", { text: "\u56DE\u6536\u7AD9\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u4F7F\u7528\u7CFB\u7EDF\u56DE\u6536\u7AD9").setDesc("\u5220\u9664\u6587\u4EF6\u5939\u65F6\u4F7F\u7528\u7CFB\u7EDF\u56DE\u6536\u7AD9").addToggle((toggle) => toggle.setValue(this.plugin.settings.useSystemTrash).onChange(async (value) => {
      this.plugin.settings.useSystemTrash = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (!this.plugin.settings.useSystemTrash) {
      new import_obsidian.Setting(containerEl).setName("\u81EA\u5B9A\u4E49\u56DE\u6536\u7AD9\u8DEF\u5F84").setDesc("\u6307\u5B9A\u81EA\u5B9A\u4E49\u56DE\u6536\u7AD9\u6587\u4EF6\u5939\u7684\u8DEF\u5F84").addText((text) => text.setPlaceholder("_\u56DE\u6536\u7AD9").setValue(this.plugin.settings.customTrashFolder).onChange(async (value) => {
        this.plugin.settings.customTrashFolder = value;
        await this.plugin.saveSettings();
      }));
    }
  }
  addAttachmentPatternSetting(containerEl, pattern, index) {
    const setting = new import_obsidian.Setting(containerEl).setName(`\u5173\u8054\u6587\u4EF6\u5939\u6A21\u5F0F ${index + 1}`).setDesc("\u8BBE\u7F6E\u4E0E\u7B14\u8BB0\u5173\u8054\u7684\u6587\u4EF6\u5939\u547D\u540D\u6A21\u5F0F\uFF0C\u4F7F\u7528 {$filename} \u4F5C\u4E3A\u7B14\u8BB0\u540D\u79F0\u7684\u5360\u4F4D\u7B26").addText((text) => text.setPlaceholder("{$filename}_\u9644\u4EF6").setValue(pattern.pattern).onChange(async (value) => {
      this.plugin.settings.attachmentFolderPatterns[index].pattern = value;
      await this.plugin.saveSettings();
    })).addToggle((toggle) => toggle.setValue(pattern.enabled).onChange(async (value) => {
      this.plugin.settings.attachmentFolderPatterns[index].enabled = value;
      await this.plugin.saveSettings();
    }));
    if (this.plugin.settings.attachmentFolderPatterns.length > 1) {
      setting.addButton((button) => button.setIcon("trash").setTooltip("\u5220\u9664\u6B64\u6A21\u5F0F").onClick(async () => {
        this.plugin.settings.attachmentFolderPatterns.splice(index, 1);
        await this.plugin.saveSettings();
        this.display();
      }));
    }
  }
  addCleanupPatternSetting(containerEl, pattern, index) {
    const setting = new import_obsidian.Setting(containerEl).setName(`\u6E05\u7406\u5339\u914D\u6A21\u5F0F ${index + 1}`).setDesc("\u8BBE\u7F6E\u8981\u6E05\u7406\u7684\u7A7A\u6587\u4EF6\u5939\u7684\u5339\u914D\u6A21\u5F0F").addText((text) => text.setPlaceholder("_\u9644\u4EF6").setValue(pattern.pattern).onChange(async (value) => {
      this.plugin.settings.cleanupPatterns[index].pattern = value;
      await this.plugin.saveSettings();
    })).addToggle((toggle) => toggle.setValue(pattern.enabled).onChange(async (value) => {
      this.plugin.settings.cleanupPatterns[index].enabled = value;
      await this.plugin.saveSettings();
    }));
    if (this.plugin.settings.cleanupPatterns.length > 1) {
      setting.addButton((button) => button.setIcon("trash").setTooltip("\u5220\u9664\u6B64\u6A21\u5F0F").onClick(async () => {
        this.plugin.settings.cleanupPatterns.splice(index, 1);
        await this.plugin.saveSettings();
        this.display();
      }));
    }
  }
};
